import type { Champion, Trait } from './types';

export const champions: Champion[] = [
    { "name": "Anivia", "traits": ["Freljord", "Invoker"], "cost": 1, "is_locked": false },
    { "name": "Blitzcrank", "traits": ["Zaun", "Juggernaut"], "cost": 1, "is_locked": false },
    { "name": "Briar", "traits": ["Noxus", "Juggernaut", "Slayer"], "cost": 1, "is_locked": false },
    { "name": "Caitlyn", "traits": ["Piltover", "Longshot"], "cost": 1, "is_locked": false },
    { "name": "Illaoi", "traits": ["Bilgewater", "Bruiser"], "cost": 1, "is_locked": false },
    { "name": "Jarvan IV", "traits": ["Demacia", "Defender"], "cost": 1, "is_locked": false },
    { "name": "Jhin", "traits": ["Ionia", "Gunslinger"], "cost": 1, "is_locked": false },
    { "name": "Kogmaw", "traits": ["Void", "Arcanist", "Longshot"], "cost": 1, "is_locked": false },
    { "name": "Lulu", "traits": ["Yordle", "Arcanist"], "cost": 1, "is_locked": false },
    { "name": "Qiyana", "traits": ["Ixtal", "Slayer"], "cost": 1, "is_locked": false },
    { "name": "Rumble", "traits": ["Yordle", "Defender"], "cost": 1, "is_locked": false },
    { "name": "Shen", "traits": ["Ionia", "Bruiser"], "cost": 1, "is_locked": false },
    { "name": "Sona", "traits": ["Demacia", "Invoker"], "cost": 1, "is_locked": false },
    { "name": "Viego", "traits": ["Shadow Isles", "Quickstriker"], "cost": 1, "is_locked": false },
    { "name": "Aphelios", "traits": ["Targon"], "cost": 2, "is_locked": false },
    { "name": "Ashe", "traits": ["Freljord", "Quickstriker"], "cost": 2, "is_locked": false },
    { "name": "Bard", "traits": ["Caretaker"], "cost": 2, "is_locked": true },
    { "name": "Chogath", "traits": ["Void", "Juggernaut"], "cost": 2, "is_locked": false },
    { "name": "Ekko", "traits": ["Zaun", "Disruptor"], "cost": 2, "is_locked": false },
    { "name": "Graves", "traits": ["Bilgewater", "Gunslinger"], "cost": 2, "is_locked": true },
    { "name": "Neeko", "traits": ["Ixtal", "Arcanist", "Defender"], "cost": 2, "is_locked": false },
    { "name": "Orianna", "traits": ["Piltover", "Invoker"], "cost": 2, "is_locked": true },
    { "name": "Poppy", "traits": ["Demacia", "Yordle", "Juggernaut"], "cost": 2, "is_locked": true },
    { "name": "RekSai", "traits": ["Void", "Vanquisher"], "cost": 2, "is_locked": false },
    { "name": "Sion", "traits": ["Noxus", "Bruiser"], "cost": 2, "is_locked": false },
    { "name": "Teemo", "traits": ["Yordle", "Longshot"], "cost": 2, "is_locked": false },
    { "name": "Tristana", "traits": ["Yordle", "Gunslinger"], "cost": 2, "is_locked": false },
    { "name": "Tryndamere", "traits": ["Freljord", "Slayer"], "cost": 2, "is_locked": true },
    { "name": "Twisted Fate", "traits": ["Bilgewater", "Quickstriker"], "cost": 2, "is_locked": false },
    { "name": "Vi", "traits": ["Piltover", "Zaun", "Defender"], "cost": 2, "is_locked": false },
    { "name": "Xin Zhao", "traits": ["Demacia", "Ionia", "Warden"], "cost": 2, "is_locked": false },
    { "name": "Yasuo", "traits": ["Ionia", "Slayer"], "cost": 2, "is_locked": false },
    { "name": "Yorick", "traits": ["Shadow Isles", "Warden"], "cost": 2, "is_locked": true },
    { "name": "Ahri", "traits": ["Ionia", "Arcanist"], "cost": 3, "is_locked": false },
    { "name": "Darius", "traits": ["Noxus", "Defender"], "cost": 3, "is_locked": true },
    { "name": "Dr Mundo", "traits": ["Zaun", "Bruiser"], "cost": 3, "is_locked": false },
    { "name": "Draven", "traits": ["Noxus", "Quickstriker"], "cost": 3, "is_locked": false },
    { "name": "Gangplank", "traits": ["Bilgewater", "Slayer", "Vanquisher"], "cost": 3, "is_locked": false },
    { "name": "Gwen", "traits": ["Shadow Isles", "Disruptor"], "cost": 3, "is_locked": true },
    { "name": "Jinx", "traits": ["Zaun", "Gunslinger"], "cost": 3, "is_locked": false },
    { "name": "Kennen", "traits": ["Ionia", "Yordle", "Defender"], "cost": 3, "is_locked": true },
    { "name": "Kobuko & Yuumi", "traits": ["Yordle", "Bruiser", "Invoker"], "cost": 3, "is_locked": true },
    { "name": "Leblanc", "traits": ["Noxus", "Invoker"], "cost": 3, "is_locked": false },
    { "name": "Leona", "traits": ["Targon"], "cost": 3, "is_locked": false },
    { "name": "Loris", "traits": ["Piltover", "Warden"], "cost": 3, "is_locked": false },
    { "name": "Malzahar", "traits": ["Void", "Disruptor"], "cost": 3, "is_locked": false },
    { "name": "Milio", "traits": ["Ixtal", "Invoker"], "cost": 3, "is_locked": false },
    { "name": "Nautilus", "traits": ["Bilgewater", "Juggernaut", "Warden"], "cost": 3, "is_locked": false },
    { "name": "Sejuani", "traits": ["Freljord", "Defender"], "cost": 3, "is_locked": false },
    { "name": "Vayne", "traits": ["Demacia", "Longshot"], "cost": 3, "is_locked": false },
    { "name": "Zoe", "traits": ["Targon"], "cost": 3, "is_locked": false },
    { "name": "Ambessa", "traits": ["Noxus", "Vanquisher"], "cost": 4, "is_locked": false },
    { "name": "Belveth", "traits": ["Void", "Slayer"], "cost": 4, "is_locked": false },
    { "name": "Braum", "traits": ["Freljord", "Warden"], "cost": 4, "is_locked": false },
    { "name": "Diana", "traits": ["Targon"], "cost": 4, "is_locked": true },
    { "name": "Fizz", "traits": ["Bilgewater", "Yordle"], "cost": 4, "is_locked": true },
    { "name": "Garen", "traits": ["Demacia", "Defender"], "cost": 4, "is_locked": false },
    { "name": "Kaisa", "traits": ["Assimilator", "Void", "Longshot"], "cost": 4, "is_locked": true },
    { "name": "Kalista", "traits": ["Shadow Isles", "Vanquisher"], "cost": 4, "is_locked": true },
    { "name": "Lissandra", "traits": ["Freljord", "Invoker"], "cost": 4, "is_locked": false },
    { "name": "Lux", "traits": ["Demacia", "Arcanist"], "cost": 4, "is_locked": false },
    { "name": "Miss Fortune", "traits": ["Bilgewater", "Gunslinger"], "cost": 4, "is_locked": false },
    { "name": "Nasus", "traits": ["Shurima"], "cost": 4, "is_locked": true },
    { "name": "Nidalee", "traits": ["Ixtal", "Huntress"], "cost": 4, "is_locked": true },
    { "name": "Renekton", "traits": ["Shurima"], "cost": 4, "is_locked": true },
    { "name": "Rift Herald", "traits": ["Void", "Bruiser"], "cost": 4, "is_locked": true },
    { "name": "Seraphine", "traits": ["Piltover", "Disruptor"], "cost": 4, "is_locked": false },
    { "name": "Singed", "traits": ["Zaun", "Juggernaut"], "cost": 4, "is_locked": true },
    { "name": "Skarner", "traits": ["Ixtal"], "cost": 4, "is_locked": true },
    { "name": "Swain", "traits": ["Noxus", "Arcanist", "Juggernaut"], "cost": 4, "is_locked": false },
    { "name": "Taric", "traits": ["Targon"], "cost": 4, "is_locked": false },
    { "name": "Veigar", "traits": ["Yordle", "Arcanist"], "cost": 4, "is_locked": true },
    { "name": "Warwick", "traits": ["Zaun", "Quickstriker"], "cost": 4, "is_locked": true },
    { "name": "Wukong", "traits": ["Ionia", "Bruiser"], "cost": 4, "is_locked": false },
    { "name": "Yone", "traits": ["Ionia", "Slayer"], "cost": 4, "is_locked": true },
    { "name": "Yunara", "traits": ["Ionia", "Quickstriker"], "cost": 4, "is_locked": false },
    { "name": "Aatrox", "traits": ["Darkin", "World Ender", "Slayer"], "cost": 5, "is_locked": true },
    { "name": "Annie", "traits": ["Dark Child", "Arcanist"], "cost": 5, "is_locked": false },
    { "name": "Azir", "traits": ["Emperor", "Shurima", "Disruptor"], "cost": 5, "is_locked": false },
    { "name": "Fiddlesticks", "traits": ["Harvester", "Vanquisher"], "cost": 5, "is_locked": false },
    { "name": "Galio", "traits": ["Demacia", "Heroic"], "cost": 5, "is_locked": true },
    { "name": "Kindred", "traits": ["Eternal", "Quickstriker"], "cost": 5, "is_locked": false },
    { "name": "Lucian & Senna", "traits": ["Soulbound", "Gunslinger"], "cost": 5, "is_locked": false },
    { "name": "Mel", "traits": ["Noxus", "Disruptor"], "cost": 5, "is_locked": true },
    { "name": "Ornn", "traits": ["Blacksmith", "Warden"], "cost": 5, "is_locked": false },
    { "name": "Sett", "traits": ["Ionia", "The Boss"], "cost": 5, "is_locked": true },
    { "name": "Shyvana", "traits": ["Dragonborn", "Juggernaut"], "cost": 5, "is_locked": false },
    { "name": "T-Hex", "traits": ["HexMech", "Piltover", "Gunslinger"], "cost": 5, "is_locked": true },
    { "name": "Tahm Kench", "traits": ["Bilgewater", "Glutton", "Bruiser"], "cost": 5, "is_locked": true },
    { "name": "Thresh", "traits": ["Shadow Isles", "Warden"], "cost": 5, "is_locked": true },
    { "name": "Volibear", "traits": ["Freljord", "Bruiser"], "cost": 5, "is_locked": true },
    { "name": "Xerath", "traits": ["Shurima", "Ascendant"], "cost": 5, "is_locked": true },
    { "name": "Ziggs", "traits": ["Yordle", "Zaun", "Longshot"], "cost": 5, "is_locked": true },
    { "name": "Zilean", "traits": ["Chronokeeper", "Invoker"], "cost": 5, "is_locked": false },
    { "name": "Aurelion Sol", "traits": ["Targon", "Star Forger"], "cost": 7, "is_locked": true },
    { "name": "Baron Nashor", "traits": ["Void", "Riftscourge"], "cost": 7, "is_locked": true },
    { "name": "Brock", "traits": ["Ixtal"], "cost": 7, "is_locked": true },
    { "name": "Ryze", "traits": ["Rune Mage"], "cost": 7, "is_locked": true },
    { "name": "Sylas", "traits": ["Chainbreaker", "Arcanist", "Defender"], "cost": 7, "is_locked": true },
    { "name": "Zaahen", "traits": ["Darkin", "Immortal"], "cost": 7, "is_locked": true }
];

export const traits: Trait[] = [
    { "name": "Ascendant", "tiers": [1] },
    { "name": "Assimilator", "tiers": [1] },
    { "name": "Bilgewater", "tiers": [3, 5, 7, 10] },
    { "name": "Blacksmith", "tiers": [1] },
    { "name": "Caretaker", "tiers": [1] },
    { "name": "Chainbreaker", "tiers": [1] },
    { "name": "Chronokeeper", "tiers": [1] },
    { "name": "Dark Child", "tiers": [1] },
    { "name": "Darkin", "tiers": [1, 2, 3] },
    { "name": "Demacia", "tiers": [3, 5, 7, 9] },
    { "name": "Arcanist", "tiers": [2, 4, 6] },
    { "name": "Bruiser", "tiers": [2, 4, 6] },
    { "name": "Defender", "tiers": [2, 4, 6] },
    { "name": "Disruptor", "tiers": [2, 4] },
    { "name": "Dragonborn", "tiers": [1] },
    { "name": "Emperor", "tiers": [1] },
    { "name": "Eternal", "tiers": [1] },
    { "name": "Freljord", "tiers": [3, 5, 7] },
    { "name": "Glutton", "tiers": [1] },
    { "name": "Gunslinger", "tiers": [2, 4] },
    { "name": "Harvester", "tiers": [1] },
    { "name": "Heroic", "tiers": [1] },
    { "name": "HexMech", "tiers": [1] },
    { "name": "Huntress", "tiers": [1] },
    { "name": "Immortal", "tiers": [1] },
    { "name": "Invoker", "tiers": [2, 4] },
    { "name": "Ionia", "tiers": [3, 5, 7, 10] },
    { "name": "Ixtal", "tiers": [3, 5, 7] },
    { "name": "Juggernaut", "tiers": [2, 4, 6] },
    { "name": "Longshot", "tiers": [2, 3, 4, 5] },
    { "name": "Noxus", "tiers": [3, 5, 7, 10] },
    { "name": "Piltover", "tiers": [2, 4, 6] },
    { "name": "Quickstriker", "tiers": [2, 3, 4, 5] },
    { "name": "Riftscourge", "tiers": [1] },
    { "name": "Rune Mage", "tiers": [1] },
    { "name": "Shadow Isles", "tiers": [2, 3, 4, 5] },
    { "name": "Shurima", "tiers": [2, 3, 4] },
    { "name": "Slayer", "tiers": [2, 4, 6] },
    { "name": "Soulbound", "tiers": [1] },
    { "name": "Star Forger", "tiers": [1] },
    { "name": "Targon", "tiers": [1] },
    { "name": "The Boss", "tiers": [1] },
    { "name": "Vanquisher", "tiers": [2, 3, 4, 5] },
    { "name": "Void", "tiers": [2, 4, 6, 9] },
    { "name": "Warden", "tiers": [2, 3, 4, 5] },
    { "name": "World Ender", "tiers": [1] },
    { "name": "Yordle", "tiers": [2, 4, 6, 8, 10] },
    { "name": "Zaun", "tiers": [3, 5, 7] }
];
